# Generated by Django 4.1.13 on 2024-07-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=50)),
                ('distribuidora', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=255)),
                ('quantidade_kw', models.FloatField()),
                ('unid_c_tributos', models.FloatField()),
                ('valor_unit', models.FloatField()),
                ('pis_cofins', models.FloatField()),
                ('base_icms', models.FloatField()),
                ('aliquota_icms', models.FloatField()),
                ('valor_icms', models.FloatField()),
                ('tarifa_unitaria', models.FloatField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='upload.cliente')),
            ],
        ),
    ]
