# Generated by Django 5.0.7 on 2024-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_conta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='distribuidora',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='modalidade',
        ),
        migrations.AddField(
            model_name='cliente',
            name='distribuidora',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='modalidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
