# Generated by Django 5.0.7 on 2024-08-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_conta_distribuidora_remove_conta_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='upload.cliente'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
