# Generated by Django 5.0.7 on 2024-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_conta_aliquota_icms_alter_conta_base_icms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='distribuidora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
