# Generated by Django 5.0.7 on 2024-08-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_cliente_distribuidora_alter_cliente_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_demanda_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_fatura',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
