# Generated by Django 5.0.7 on 2024-08-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_cliente_ano_cliente_mes_cliente_valor_demanda_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='upload.cliente'),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('valor_fatura', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('valor_demanda_max', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='upload.cliente')),
            ],
        ),
    ]
