# Generated by Django 5.0.7 on 2024-08-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_alter_conta_cliente_fatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='valor_demanda_max',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='valor_fatura',
        ),
    ]
