# Generated by Django 5.0.7 on 2024-08-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_remove_cliente_ano_remove_cliente_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='mes',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
