# Generated by Django 4.2.15 on 2024-08-31 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_alter_fatura_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_fat', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_kw', models.FloatField(blank=True, null=True)),
                ('unit_c_trib', models.FloatField(blank=True, null=True)),
                ('aliquota_icms', models.FloatField(blank=True, null=True)),
                ('aliquota_pis', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacao', to='upload.cliente')),
            ],
        ),
    ]
