# Generated by Django 4.2.15 on 2024-09-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_simulacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_leitura', models.CharField(blank=True, max_length=100, null=True)),
                ('fim_leitura', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('fator_carga', models.CharField(blank=True, max_length=100, null=True)),
                ('consumo', models.CharField(blank=True, max_length=100, null=True)),
                ('custo_medio', models.CharField(blank=True, max_length=100, null=True)),
                ('concessionaria', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafat', to='upload.cliente')),
            ],
        ),
    ]
