# Generated by Django 4.2.15 on 2024-09-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_dadosmedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfatura',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
