# Generated by Django 4.2.15 on 2024-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_alter_dadosfatura_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enel_tranding', models.FloatField(blank=True, null=True)),
                ('cativo_total', models.FloatField(blank=True, null=True)),
                ('cativo_fat', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
