# Generated by Django 4.2.15 on 2024-09-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_dadoseconomia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoseconomia',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dataecon', to='upload.cliente'),
            preserve_default=False,
        ),
    ]
